%
% This file is part of La Machine
%
% Copyright 2024-2025 Olivier Mével <olivier@multiplie.fr>
%                     Paul Guyot <pguyot@kallisys.net>
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
%    http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
%
% SPDX-License-Identifier: Apache-2.0
%

-module(la_machine_scenarios).

-ifdef(TEST).
-include_lib("eunit/include/eunit.hrl").
-endif.

-export([
    count/1,
    get/2
]).

-export([
    scenario_play_1_buzziV/0,
    scenario_play_2/0,
    scenario_play_3_glouglou/0,
    scenario_play_4_bouchon/0,
    scenario_play_5_beepV/0,

    scenario_play_0_count/0,

    scenario_poke/0,

    scenario_meuh_5/0,
    scenario_meuh_6/0
]).

-export_type([
    scenario/0
]).

-type scenario() :: [scenario_part()].
-type scenario_part() :: [scenario_element()].
-type scenario_element() ::
    {servo, non_neg_integer()}
    | {aac, binary()}
    | {wait, non_neg_integer() | sound}.

% To save memory and leverage mmap, each scenario is a dedicated exported
% function, named "scenario_<type>".
% Suffixes are ignored but scenarios are sorted lexicographically to get
% ith scenario with get/2.

-spec count(atom()) -> non_neg_integer().
count(Type) ->
    Prefix = "scenario_" ++ atom_to_list(Type),
    PrefixLen = length(Prefix),
    Exports = ?MODULE:module_info(exports),
    lists:foldl(
        fun(Export, AccCount) ->
            case Export of
                {FuncName, 0} ->
                    FuncPrefix = lists:sublist(atom_to_list(FuncName), PrefixLen),
                    if
                        FuncPrefix =:= Prefix -> AccCount + 1;
                        true -> AccCount
                    end;
                {_FuncName, _OtherArity} ->
                    AccCount
            end
        end,
        0,
        Exports
    ).

-spec get(atom(), pos_integer()) -> scenario().
get(Type, Ith) ->
    Prefix = "scenario_" ++ atom_to_list(Type),
    PrefixLen = length(Prefix),
    Exports = ?MODULE:module_info(exports),
    AllOfType = lists:foldl(
        fun(Export, AccL) ->
            case Export of
                {FuncName, 0} ->
                    FuncPrefix = lists:sublist(atom_to_list(FuncName), PrefixLen),
                    if
                        FuncPrefix =:= Prefix -> [FuncName | AccL];
                        true -> AccL
                    end;
                {_FuncName, _OtherArity} ->
                    AccL
            end
        end,
        [],
        Exports
    ),
    Sorted = lists:sort(AllOfType),
    Selected = lists:nth(Ith, Sorted),
    ?MODULE:Selected().

scenario_play_1_buzziV() ->
    [
        [
            {servo, 20},
            {wait, 1000},
            {aac, <<"hits/tt_buzziV.aac">>},
            {wait, 10},
            {servo, 100},
            {wait, 1000},
            {servo, 0}
        ]
    ].

scenario_play_2() ->
    [
        [
            {servo, 20},
            {aac, <<"gears/tt_1306.aac">>},
            {servo, 53.0},
            {wait, 84},
            {servo, 54.0},
            {wait, 84},
            {servo, 56.0},
            {wait, 84},
            {servo, 56.0},
            {wait, 83},
            {servo, 57.0},
            {wait, 84},
            {servo, 57.0},
            {wait, 84},
            {servo, 57.0},
            {wait, 83},
            {servo, 56.0},
            {wait, 83},
            {servo, 57.0},
            {wait, 83},
            {servo, 57.0},
            {wait, 83},
            {servo, 58.0},
            {wait, 83},
            {servo, 58.0},
            {wait, 83},
            {servo, 57.0},
            {wait, 83},
            {servo, 59.0},
            {wait, 83},
            {servo, 59.0},
            {wait, 84},
            {servo, 59.0},
            {wait, 84},
            {servo, 59.0},
            {wait, 84},
            {servo, 60.0},
            {wait, 84},
            {servo, 60.0},
            {wait, 84},
            {servo, 61.0},
            {wait, 84},
            {servo, 61.0},
            {wait, 84},
            {servo, 61.0},
            {wait, 84},
            {servo, 62.0},
            {wait, 84},
            {servo, 63.0},
            {wait, 84},
            {servo, 64.0},
            {wait, 84},
            {servo, 64.0},
            {wait, 84},
            {servo, 66.0},
            {wait, 84},
            {servo, 66.0},
            {wait, 84},
            {servo, 68.0},
            {wait, 84},
            {servo, 68.0},
            {wait, 84},
            {servo, 69.0},
            {wait, 84},
            {servo, 70.0},
            {wait, 84},
            {servo, 72.0},
            {wait, 84},
            {servo, 73.0},
            {wait, 84},
            {servo, 74.0},
            {wait, 84},
            {servo, 75.0},
            {wait, 84},
            {servo, 76.0},
            {wait, 83},
            {servo, 77.0},
            {wait, 83},
            {servo, 79.0},
            {wait, 84},
            {servo, 80.0},
            {wait, 84},
            {servo, 82.0},
            {wait, 84},
            {servo, 83.0},
            {wait, 84},
            {servo, 83.0},
            {wait, 84},
            {servo, 84.0},
            {wait, 84},
            {servo, 83.0},
            {wait, 84},
            {servo, 83.0},
            {wait, 84},
            {servo, 83.0},
            {wait, 84},
            {servo, 83.0},
            {wait, 84},
            {servo, 85.0},
            {wait, 84},
            {servo, 86.0},
            {wait, 84},
            {servo, 86.0},
            {wait, 84},
            {servo, 87.0},
            {wait, 84},
            {servo, 88.0},
            {wait, 84},
            {servo, 88.0},
            {wait, 84},
            {servo, 89.0},
            {wait, 84},
            {servo, 89.0},
            {wait, 84},
            {servo, 88.0},
            {wait, 84},
            {servo, 90.0},
            {wait, 84},
            {servo, 90.0},
            {wait, 84},
            {servo, 90.0},
            {wait, 84},
            {servo, 91.0},
            {wait, 84},
            {servo, 90.0},
            {wait, 84},
            {servo, 91.0},
            {wait, 84},
            {servo, 92.0},
            {wait, 84},
            {servo, 91.0},
            {wait, 84},
            {servo, 92.0},
            {wait, 84},
            {servo, 92.0},
            {wait, 84},
            {servo, 92.0},
            {wait, 84},
            {servo, 92.0},
            {wait, 84},
            {servo, 92.0},
            {wait, 84},
            {servo, 92.0},
            {wait, 84},
            {servo, 92.0},
            {wait, 84},
            {servo, 92.0},
            {wait, 84},
            {servo, 92.0},
            {wait, 84},
            {servo, 92.0},
            {wait, 84},
            {servo, 93.0},
            {wait, sound},
            {wait, 1000},
            {aac, <<"hits/tt_buzzoV.aac">>},
            {wait, 10},
            {servo, 100},
            {wait, 1000},
            {servo, 0}
        ]
    ].

scenario_play_3_glouglou() ->
    [
        [
            {servo, 20},
            {aac, <<"gears/tt_1105_glouglou.aac">>},
            {servo, 49},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 61},
            {wait, 100},
            {servo, 40},
            {wait, 100},
            {servo, 28},
            {wait, 100},
            {servo, 28},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 70},
            {wait, 100},
            {servo, 39},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 62},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 73},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 62},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 68},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 82},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 70},
            {wait, 100},
            {servo, 51},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 75},
            {wait, 100},
            {servo, 51},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 80},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 48},
            {wait, 100},
            {servo, 49},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 64},
            {wait, 100},
            {servo, 59},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 68},
            {wait, 100},
            {servo, 83},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 73},
            {wait, 100},
            {servo, 54},
            {wait, 100},
            {servo, 63},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 67},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 57},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 77},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 78},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 87},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 69},
            {wait, 100},
            {servo, 70},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 69},
            {wait, 100},
            {servo, 89},
            {wait, 100},
            {servo, 29},
            {wait, 100},
            {servo, 28},
            {wait, 100},
            {servo, 51},
            {wait, 100},
            {servo, 28},
            {wait, 100},
            {servo, 38},
            {wait, 100},
            {servo, 30},
            {wait, 100},
            {servo, 28},
            {wait, 100},
            {servo, 28},
            {wait, 100},
            {wait, sound},
            {wait, 1000},
            {aac, <<"hits/tt_buzziV.aac">>},
            {wait, 10},
            {servo, 100},
            {wait, 1000},
            {servo, 0}
        ]
    ].

scenario_play_4_bouchon() ->
    [
        [
            {servo, 20},
            {aac, <<"gears/tt_1340.aac">>},
            {servo, 30},
            {wait, 83},
            {servo, 30},
            {wait, 84},
            {servo, 30},
            {wait, 83},
            {servo, 30},
            {wait, 83},
            {servo, 30},
            {wait, 84},
            {servo, 30},
            {wait, 83},
            {servo, 30},
            {wait, 83},
            {servo, 30},
            {wait, 84},
            {servo, 30},
            {wait, 83},
            {servo, 30},
            {wait, 83},
            {servo, 30},
            {wait, 84},
            {servo, 47},
            {wait, 83},
            {servo, 45},
            {wait, 84},
            {servo, 43},
            {wait, 84},
            {servo, 42},
            {wait, 83},
            {servo, 42},
            {wait, 84},
            {servo, 45},
            {wait, 84},
            {servo, 57},
            {wait, 84},
            {servo, 52},
            {wait, 83},
            {servo, 42},
            {wait, 84},
            {servo, 51},
            {wait, 84},
            {servo, 63},
            {wait, 84},
            {servo, 54},
            {wait, 84},
            {servo, 44},
            {wait, 84},
            {servo, 42},
            {wait, 83},
            {servo, 53},
            {wait, 84},
            {servo, 65},
            {wait, 84},
            {servo, 67},
            {wait, 83},
            {servo, 55},
            {wait, 84},
            {servo, 42},
            {wait, 84},
            {servo, 44},
            {wait, 84},
            {servo, 57},
            {wait, 84},
            {servo, 66},
            {wait, 84},
            {servo, 69},
            {wait, 83},
            {servo, 66},
            {wait, 84},
            {servo, 64},
            {wait, 84},
            {servo, 63},
            {wait, 83},
            {servo, 51},
            {wait, 84},
            {servo, 46},
            {wait, 84},
            {servo, 63},
            {wait, 83},
            {servo, 55},
            {wait, 84},
            {servo, 45},
            {wait, 84},
            {servo, 58},
            {wait, 84},
            {servo, 64},
            {wait, 84},
            {servo, 44},
            {wait, 84},
            {servo, 52},
            {wait, 84},
            {servo, 68},
            {wait, 84},
            {servo, 69},
            {wait, 84},
            {servo, 69},
            {wait, 84},
            {servo, 68},
            {wait, 84},
            {servo, 58},
            {wait, 83},
            {servo, 48},
            {wait, 84},
            {servo, 65},
            {wait, 84},
            {servo, 65},
            {wait, 84},
            {servo, 46},
            {wait, 84},
            {servo, 47},
            {wait, 84},
            {servo, 66},
            {wait, 84},
            {servo, 67},
            {wait, 83},
            {servo, 55},
            {wait, 84},
            {servo, 45},
            {wait, 84},
            {servo, 58},
            {wait, 83},
            {servo, 70},
            {wait, 84},
            {servo, 67},
            {wait, 83},
            {servo, 49},
            {wait, 84},
            {servo, 42},
            {wait, 84},
            {servo, 48},
            {wait, 83},
            {servo, 49},
            {wait, 84},
            {servo, 56},
            {wait, 84},
            {servo, 72},
            {wait, 83},
            {servo, 71},
            {wait, 84},
            {servo, 69},
            {wait, 84},
            {servo, 66},
            {wait, 83},
            {servo, 49},
            {wait, 84},
            {servo, 44},
            {wait, 84},
            {servo, 62},
            {wait, 83},
            {servo, 61},
            {wait, 84},
            {servo, 44},
            {wait, 84},
            {servo, 48},
            {wait, 83},
            {servo, 62},
            {wait, 84},
            {servo, 46},
            {wait, 84},
            {servo, 44},
            {wait, 83},
            {servo, 61},
            {wait, 84},
            {servo, 66},
            {wait, 84},
            {servo, 65},
            {wait, 84},
            {servo, 65},
            {wait, 84},
            {servo, 63},
            {wait, 84},
            {servo, 46},
            {wait, 84},
            {servo, 48},
            {wait, 83},
            {servo, 65},
            {wait, 84},
            {servo, 48},
            {wait, 84},
            {servo, 40},
            {wait, 83},
            {servo, 41},
            {wait, 84},
            {servo, 51},
            {wait, 84},
            {servo, 67},
            {wait, 83},
            {servo, 61},
            {wait, 84},
            {servo, 44},
            {wait, 84},
            {servo, 42},
            {wait, 83},
            {servo, 50},
            {wait, 84},
            {servo, 66},
            {wait, 83},
            {servo, 57},
            {wait, 84},
            {servo, 43},
            {wait, 84},
            {servo, 42},
            {wait, 83},
            {servo, 43},
            {wait, 84},
            {servo, 61},
            {wait, 84},
            {servo, 65},
            {wait, 84},
            {servo, 65},
            {wait, 84},
            {servo, 62},
            {wait, 84},
            {servo, 48},
            {wait, 83},
            {servo, 42},
            {wait, 84},
            {servo, 57},
            {wait, 84},
            {servo, 58},
            {wait, 83},
            {servo, 43},
            {wait, 84},
            {servo, 47},
            {wait, 84},
            {servo, 60},
            {wait, 83},
            {servo, 47},
            {wait, 84},
            {servo, 41},
            {wait, 84},
            {servo, 57},
            {wait, 83},
            {servo, 64},
            {wait, 84},
            {servo, 63},
            {wait, 84},
            {servo, 61},
            {wait, 83},
            {servo, 55},
            {wait, 84},
            {servo, 42},
            {wait, 84},
            {servo, 51},
            {wait, 83},
            {servo, 63},
            {wait, 84},
            {servo, 44},
            {wait, 84},
            {servo, 38},
            {wait, 84},
            {servo, 40},
            {wait, 84},
            {servo, 58},
            {wait, 84},
            {servo, 63},
            {wait, 84},
            {servo, 47},
            {wait, 83},
            {servo, 38},
            {wait, 84},
            {servo, 37},
            {wait, 83},
            {servo, 42},
            {wait, 84},
            {wait, sound},
            {wait, 1000},
            {aac, <<"hits/tt_bouchonV.aac">>},
            {wait, 200},
            {servo, 100},
            {servo, 100},
            {wait, 100},
            {servo, 95},
            {wait, 100},
            {servo, 90},
            {wait, 100},
            {servo, 85},
            {wait, 100},
            {servo, 80},
            {wait, 100},
            {servo, 75},
            {wait, 100},
            {servo, 70},
            {wait, 100},
            {servo, 65},
            {wait, 100},
            {servo, 60},
            {wait, 100},
            {servo, 55},
            {wait, 100},
            {servo, 50},
            {wait, 100},
            {servo, 45},
            {wait, 100},
            {servo, 40},
            {wait, 100},
            {servo, 35},
            {wait, 100},
            {servo, 30},
            {wait, 100},
            {servo, 25},
            {wait, 100},
            {servo, 20},
            {wait, 100},
            {servo, 15},
            {wait, 100},
            {servo, 10},
            {wait, 100},
            {servo, 5},
            {wait, 100},
            {servo, 0}
        ]
    ].

scenario_play_5_beepV() ->
    [
        [
            {servo, 20},
            {aac, <<"gears/tt_0987.aac">>},
            {servo, 44},
            {wait, 300},
            {servo, 43},
            {wait, 300},
            {servo, 89},
            {wait, 300},
            {servo, 89},
            {wait, 300},
            {servo, 83},
            {wait, 300},
            {servo, 51},
            {wait, 300},
            {servo, 44},
            {wait, 300},
            {servo, 89},
            {wait, 300},
            {servo, 89},
            {wait, 300},
            {servo, 82},
            {wait, 300},
            {servo, 72},
            {wait, 300},
            {servo, 48},
            {wait, 300},
            {servo, 89},
            {wait, 300},
            {servo, 89},
            {wait, 300},
            {servo, 78},
            {wait, 300},
            {servo, 69},
            {wait, 300},
            {servo, 44},
            {wait, 300},
            {servo, 89},
            {wait, 300},
            {servo, 89},
            {wait, 300},
            {servo, 83},
            {wait, 300},
            {servo, 54},
            {wait, 300},
            {servo, 46},
            {wait, 300},
            {servo, 89},
            {wait, 300},
            {servo, 89},
            {wait, 300},
            {servo, 76},
            {wait, 300},
            {servo, 89},
            {wait, 300},
            {servo, 67},
            {wait, 300},
            {servo, 89},
            {wait, 300},
            {servo, 58},
            {wait, 300},
            {servo, 28},
            {wait, 300},
            {servo, 28},
            {wait, 300},
            {servo, 89},
            {wait, 300},
            {wait, sound},
            {wait, 1000},
            {aac, <<"hits/tt_beepV.aac">>},
            {servo, 100},
            {wait, 706},
            {servo, 100},
            {wait, 100},
            {servo, 98},
            {wait, 100},
            {servo, 96},
            {wait, 100},
            {servo, 94},
            {wait, 100},
            {servo, 92},
            {wait, 100},
            {servo, 90},
            {wait, 100},
            {servo, 88},
            {wait, 100},
            {servo, 86},
            {wait, 100},
            {servo, 84},
            {wait, 100},
            {servo, 82},
            {wait, 100},
            {servo, 80},
            {wait, 100},
            {servo, 78},
            {wait, 100},
            {servo, 76},
            {wait, 100},
            {servo, 74},
            {wait, 100},
            {servo, 72},
            {wait, 100},
            {servo, 70},
            {wait, 100},
            {servo, 68},
            {wait, 100},
            {servo, 66},
            {wait, 100},
            {servo, 64},
            {wait, 100},
            {servo, 62},
            {wait, 100},
            {servo, 60},
            {wait, 100},
            {servo, 58},
            {wait, 100},
            {servo, 56},
            {wait, 100},
            {servo, 54},
            {wait, 100},
            {servo, 52},
            {wait, 100},
            {servo, 50},
            {wait, 100},
            {servo, 48},
            {wait, 100},
            {servo, 46},
            {wait, 100},
            {servo, 44},
            {wait, 100},
            {servo, 42},
            {wait, 100},
            {servo, 40},
            {wait, 100},
            {servo, 38},
            {wait, 100},
            {servo, 36},
            {wait, 100},
            {servo, 34},
            {wait, 100},
            {servo, 32},
            {wait, 100},
            {servo, 30},
            {wait, 100},
            {servo, 28},
            {wait, 100},
            {servo, 26},
            {wait, 100},
            {servo, 24},
            {wait, 100},
            {servo, 22},
            {wait, 100},
            {servo, 20},
            {wait, 100},
            {servo, 18},
            {wait, 100},
            {servo, 16},
            {wait, 100},
            {servo, 14},
            {wait, 100},
            {servo, 12},
            {wait, 100},
            {servo, 10},
            {wait, 100},
            {servo, 8},
            {wait, 100},
            {servo, 6},
            {wait, 100},
            {servo, 4},
            {wait, 100},
            {servo, 2},
            {wait, 100},
            {servo, 0}
        ]
    ].

scenario_play_0_count() ->
    [
        [
            {servo, 20},
            {wait, 1000},
            {aac, <<"gears/all-together-one.aac">>},
            {wait, 10},
            {servo, 100},
            {wait, sound},
            {servo, 0}
        ],
        [
            {servo, 20},
            {wait, 1000},
            {aac, <<"gears/all-together-one-two.aac">>},
            {wait, 10},
            {servo, 100},
            {wait, sound},
            {servo, 0}
        ],
        [
            {servo, 20},
            {wait, 1000},
            {aac, <<"gears/all-together-one-two-three.aac">>},
            {wait, 10},
            {servo, 100},
            {wait, sound},
            {servo, 0}
        ],
        [
            {servo, 20},
            {wait, 1000},
            {aac, <<"gears/all-together-one-two-three-four.aac">>},
            {wait, 10},
            {servo, 100},
            {wait, sound},
            {servo, 0}
        ],
        [
            {servo, 20},
            {wait, 1000},
            {aac, <<"gears/all-together-one-two-three-four-can-i-have.aac">>},
            {wait, 10},
            {servo, 100},
            {wait, sound},
            {servo, 0}
        ]
    ].

scenario_poke() ->
    [
        [
            {servo, 55},
            {wait, 100},
            {servo, 40},
            {wait, 100},
            {servo, 40},
            {wait, 100},
            {servo, 55},
            {wait, 100},
            {servo, 40},
            {wait, 100},
            {servo, 40},
            {wait, 100},
            {servo, 59},
            {wait, 100},
            {servo, 40},
            {wait, 100},
            {servo, 40},
            {wait, 100},
            {servo, 51},
            {wait, 100},
            {servo, 40},
            {wait, 100},
            {servo, 40},
            {wait, 100},
            {servo, 58},
            {wait, 100},
            {servo, 40},
            {wait, 100},
            {servo, 51},
            {wait, 100},
            {servo, 40},
            {wait, 100},
            {servo, 40},
            {wait, 100},
            {servo, 58},
            {wait, 100},
            {servo, 95},
            {wait, 3000},
            {aac, <<"poke/tt_coucou_poke.aac">>},
            {wait, 500},
            {servo, 0}
        ]
    ].

scenario_meuh_5() ->
    [
        [
            {aac, <<"meuh/meuh-5.aac">>},
            {wait, sound}
        ]
    ].

scenario_meuh_6() ->
    [
        [
            {aac, <<"meuh/meuh-6.aac">>},
            {wait, sound}
        ]
    ].

-ifdef(TEST).
count_test_() ->
    [
        ?_assertEqual(6, count(play)),
        ?_assertEqual(1, count(poke)),
        ?_assertEqual(0, count(moocow))
    ].

get_test_() ->
    [
        ?_assertEqual({aac, <<"hits/tt_buzziV.aac">>}, lists:nth(3, hd(get(play, 2)))),
        ?_assertEqual({aac, <<"gears/tt_0987.aac">>}, lists:nth(2, hd(get(play, 6))))
    ].
-endif.
