# SPDX-License-Identifier: Apache-2.0
name: Build
on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  erlfmt:
    runs-on: ubuntu-latest
    container: erlang:27
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run erlfmt
      run: |
        rebar3 as check fmt --check

  eunit:
    runs-on: ubuntu-latest
    container: erlang:27
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run eunit
      run: |
        rebar3 eunit

  dialyzer:
    runs-on: ubuntu-latest
    container: erlang:27
    steps:
    - name: Checkout AtomVM
      uses: actions/checkout@v4
      with:
        repository: atomvm/AtomVM
        path: AtomVM
        ref: release-0.6

    - name: Checkout atomvm_esp_adf
      uses: actions/checkout@v4
      with:
        path: la_machine

    - name: Install dependencies to build AtomVM libraries
      run: |
        set -eu
        apt update
        DEBIAN_FRONTEND=noninteractive apt install -y -q \
            doxygen gcc g++ zlib1g-dev libmbedtls-dev make cmake gperf

    - name: Build AtomVM libraries
      shell: bash
      working-directory: AtomVM/
      run: |
        mkdir build
        cd build
        cmake ..
        cd libs
        make

    - name: Build La Machine's dependencies
      run: |
        cd la_machine
        rebar3 compile -d

    - name: Build PLT
      run: |
        cd la_machine
        dialyzer --build_plt --output_plt la_machine_deps.plt ../AtomVM/build/libs/estdlib/src/beams ../AtomVM/build/libs/eavmlib/src/beams _build/default/lib/atomvm_esp_adf/ebin/

    - name: Run dialyzer using source code
      run: |
        cd la_machine
        dialyzer --plt la_machine_deps.plt --src src/

    # We don't need Elixir and Alisp and could save few bytes by not including them
    - name: Upload AtomVM eavmlib.avm
      uses: actions/upload-artifact@v4
      with:
        name: eavmlib.avm
        path:  AtomVM/build/libs/eavmlib/src/eavmlib.avm
        if-no-files-found: error
        retention-days: 1

    - name: Upload AtomVM estdlib.avm
      uses: actions/upload-artifact@v4
      with:
        name: estdlib.avm
        path:  AtomVM/build/libs/estdlib/src/estdlib.avm
        if-no-files-found: error
        retention-days: 1

  packbeam:
    needs: dialyzer
    runs-on: ubuntu-latest
    container: erlang:27
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download AtomVM eavmlib.avm
      uses: actions/download-artifact@v4
      with:
        name: eavmlib.avm
        path: eavmlib

    - name: Download AtomVM estdlib.avm
      uses: actions/download-artifact@v4
      with:
        name: estdlib.avm
        path: estdlib

    - name: Run packbeam
      run: |
        rebar3 atomvm packbeam -p -e `pwd`/eavmlib/eavmlib.avm -e `pwd`/estdlib/estdlib.avm

    - name: Upload la_machine.avm
      uses: actions/upload-artifact@v4
      with:
        name: la_machine.avm
        path: _build/default/lib/la_machine.avm
        if-no-files-found: error
        retention-days: 1

  build_vm:
    runs-on: ubuntu-latest
    container: espressif/idf:v5.2.2
    steps:
    - name: Checkout La Machine
      uses: actions/checkout@v4
      with:
        path: la_machine

    - name: Checkout AtomVM
      uses: actions/checkout@v4
      with:
        repository: atomvm/AtomVM
        path: AtomVM
        ref: release-0.6

    - name: Checkout atomvm_esp_adf
      uses: actions/checkout@v4
      with:
        repository: pguyot/atomvm_esp_adf
        path: AtomVM/src/platforms/esp32/components/atomvm_esp_adf/

    - name: Checkout atomvm_esp_adf submodules
      shell: bash
      working-directory: AtomVM/src/platforms/esp32/components/atomvm_esp_adf/
      run: |
        git submodule update --init components/esp-adf
        cd components/esp-adf
        git submodule update --init components/esp-adf-libs/

    - name: Build esp32c3 binary with idf.py
      shell: bash
      working-directory: AtomVM/src/platforms/esp32/
      run: |
        cp sdkconfig.release-defaults sdkconfig.defaults
        rm -rf build
        . $IDF_PATH/export.sh
        idf.py set-target esp32c3
        echo CONFIG_FREERTOS_ENABLE_BACKWARD_COMPATIBILITY=y >> sdkconfig
        echo CONFIG_AVM_ENABLE_NETWORK_PORT_DRIVER=n >> sdkconfig
        echo CONFIG_AVM_ENABLE_SOCKET_PORT_DRIVER=n >> sdkconfig
        echo CONFIG_AVM_ENABLE_OTP_SOCKET_NIFS=n >> sdkconfig
        echo CONFIG_AVM_ENABLE_OTP_NET_NIFS=n >> sdkconfig
        echo CONFIG_AVM_ENABLE_OTP_SSL_NIFS=n >> sdkconfig
        echo CONFIG_AVM_ESP_ADF_PWM_OUTPUT_ENABLE=n >> sdkconfig
        # https://github.com/atomvm/AtomVM/pull/1198
        # echo CONFIG_AVM_ENABLE_GPIO_PORT_DRIVER=n >> sdkconfig
        echo CONFIG_AVM_ENABLE_UART_PORT_DRIVER=n >> sdkconfig
        idf.py build

    - name: Build la machine partitions map
      shell: bash
      working-directory: la_machine/image/
      run: |
        python $IDF_PATH/components/partition_table/gen_esp32part.py partitions.csv partitions.bin

    - name: Upload bootloader
      uses: actions/upload-artifact@v4
      with:
        name: bootloader.bin
        path: AtomVM/src/platforms/esp32/build/bootloader/bootloader.bin
        if-no-files-found: error
        retention-days: 1

    - name: Upload mkimage script
      uses: actions/upload-artifact@v4
      with:
        name: mkimage.erl
        path: AtomVM/src/platforms/esp32/build/mkimage.erl
        if-no-files-found: error
        retention-days: 1

    - name: Upload VM
      uses: actions/upload-artifact@v4
      with:
        name: la_machine-atomvm.bin
        path: AtomVM/src/platforms/esp32/build/atomvm-esp32.bin
        if-no-files-found: error
        retention-days: 1

    - name: Upload partition map
      uses: actions/upload-artifact@v4
      with:
        name: partitions.bin
        path: la_machine/image/partitions.bin
        if-no-files-found: error
        retention-days: 1

  make_image:
    needs: [packbeam, build_vm]
    runs-on: ubuntu-latest
    container: erlang:27
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download bootloader
      uses: actions/download-artifact@v4
      with:
        name: bootloader.bin
        path: image/

    - name: Download partition map
      uses: actions/download-artifact@v4
      with:
        name: partitions.bin
        path: image/

    - name: Download VM
      uses: actions/download-artifact@v4
      with:
        name: la_machine-atomvm.bin
        path: image/

    - name: Download Packbeam
      uses: actions/download-artifact@v4
      with:
        name: la_machine.avm
        path: image/

    - name: Download mkimage script
      uses: actions/download-artifact@v4
      with:
        name: mkimage.erl
        path: image/

    - name: Build image
      shell: bash
      working-directory: image
      run: |
        find .
        escript mkimage.erl --root_dir . --config mkimage.config --out la_machine.img

    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: la_machine.img
        path: image/la_machine.img
        if-no-files-found: error
